language: objective-c
osx_image: xcode7.2
xcode_project: FoodMob.xcodeproj
xcode_scheme: FoodMob
xcode_sdk: iphonesimulator9.2

env:
  global:
    - ONLY_ACTIVE_ARCH=NO
  matrix:
    - NAME='iPhone 4s'
    - NAME='iPhone 5'
    - NAME='iPhone 5s'
    - NAME='iPhone 6'
    - NAME='iPhone 6s Plus'

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - brew outdated carthage || brew upgrade carthage
    - carthage bootstrap --verbose --platform iOS

script:
  xctool -sdk iphonesimulator9.2 -destination "platform=iOS Simulator,name=$NAME,OS=9.2" -project FoodMob.xcodeproj -scheme FoodMob test
