language: objective-c
osx_image: xcode7.2
xcode_project: FoodMob.xcodeproj
xcode_scheme: FoodMobTests
xcode_sdk: iphonesimulator9.2

before_install:
    - brew update
    - brew install carthage
    - carthage bootstrap --verbose
