//
//  FoodCategories.swift
//  FoodMob
//
//  Created by Jonathan Jemson on 2/10/16.
//  Copyright © 2016 FoodMob. All rights reserved.
//

import Foundation

public enum FoodCategories {
    case Afghan
    case Caribbean
    case HotDogs
    case African
    case Catalan
    case HotPot
    case AmericanNew
    case Cheesesteaks
    case Hungarian
    case AmericanTraditional
    case ChickenWings
    case Iberian
    case Arabian
    case Chinese
    case Indian
    case Argentine
    case ComfortFood
    case Indonesian
    case Armenian
    case Creperies
    case Irish
    case AsianFusion
    case Cuban
    case Italian
    case Australian
    case Czech
    case Japanese
    case Austrian
    case Delis
    case Korean
    case Bangladeshi
    case Diners
    case Kosher
    case Barbeque
    case Ethiopian
    case Laotian
    case Basque
    case FastFood
    case LatinAmerican
    case Belgian
    case Filipino
    case LiveRawFood
    case Brasseries
    case FishAndChips
    case Malaysian
    case Brazilian
    case Fondue
    case Mediterranean
    case BreakfastAndBrunch
    case FoodCourt
    case Mexican
    case British
    case FoodStands
    case MiddleEastern
    case Buffets
    case French
    case ModernEuropean
    case Burgers
    case Gastropubs
    case Mongolian
    case Burmese
    case German
    case Pakistani
    case Cafes
    case GlutenFree
    case PersianAndIranian
    case Cafeteria
    case Greek
    case Peruvian
    case CajunAndCreole
    case Halal
    case Pizza
    case Cambodian
    case Hawaiian
    case HimalayanAndNepalese
    case Polish
    case Portuguese
    case Russian
    case Salad
    case Sandwiches
    case Scandinavian
    case Scottish
    case Seafood
    case Singaporean
    case Slovakian
    case SoulFood
    case Soup
    case Southern
    case Spanish
    case Steakhouses
    case SushiBars
    case Taiwanese
    case TapasBars
    case TapasAndSmallPlates
    case TexMex
    case Thai
    case Turkish
    case Ukrainian
}